"""create item table

Revision ID: 73f1cf61dbfa
Revises: 
Create Date: 2025-07-25 16:22:03.661563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table, column, Integer, String, Float
from sqlalchemy.sql import insert

# revision identifiers, used by Alembic.
revision: str = '73f1cf61dbfa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.create_table(
        'items',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('price', sa.Float(), nullable=True),
        sa.Column('description', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Seed data
    item_table = table('items',
        column('id', sa.Integer),
        column('name', sa.String),
        column('price', sa.Float),
        column('description', sa.String),
    )

    op.bulk_insert(item_table, [
        {"id": 1, "name": "Laptop", "price": 75000.0, "description": "A gaming laptop"},
        {"id": 2, "name": "Mouse", "price": 500.0, "description": "Wireless mouse"},
        {"id": 3, "name": "Keyboard", "price": 1500.0, "description": "Mechanical keyboard"},
    ])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
